services:
  music-service-db:
    image: postgres:16.0
    container_name: music-service-db
    env_file:
      - $PWD/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/:/data/
    ports:
      - "5432:5432"
    networks:
        - my_persistent_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    restart: always
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SERVER_ROOT_URL: http://localhost:3000/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana-data:/var/lib/grafana  # отдельный том для Grafana
    depends_on:
      - music-service-db
    networks:
      - my_persistent_network

networks:
  my_persistent_network:
    driver: bridge

volumes:
  db-data:
    name: music-service-db-volume  # том для базы данных
  grafana-data:
    name: grafana-db-volume  # отдельный том для данных Grafana
