services:
  music-service-db:
    image: postgres:16.0
    container_name: music-service-db
    env_file:
      - $PWD/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/:/data/
    ports:
      - "5432:5432"

volumes:
  db-data:
    name: music-service-db-volume
