DROP TABLE IF EXISTS tracks_by_artists;

DROP TABLE IF EXISTS user_playlists;

DROP TABLE IF EXISTS album_tracks;

DROP TABLE IF EXISTS playlist_tracks;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS playlists;

DROP TABLE IF EXISTS tracks;

DROP TABLE IF EXISTS albums;

DROP TABLE IF EXISTS artists;